-- 산술연산 활용
SELECT A.SAL, A.SAL +(A.SAL*0.1) AS NEW_SAL,     -- 연봉상승
A.HIREDATE, A.HIREDATE +1 AS HIREDATE_PLUS_1DAY, -- +1이 1DYA로 됨
A.HIREDATE - 1/24/60/60 AS HIREDATE_MINUS_1SEC,  -- 1 / 24H / 60M / 60S 라 1SEC가 됨
A.HIREDATE - DATE'1980-02-01' AS DIFF_DAYS       -- 날짜 - 날짜
FROM EMP A;

-- || 연산자 활용(많이 사용함)
SELECT A.EMPNO, A.ENAME, A.DEPTNO, 
A.EMPNO || '번 사원의 이름은 ' || A.ENAME || '이고,' || A.DEPTNO || '번 부서 소속입니다' AS EMPLOYEE_INFO
FROM EMP A;

-- NULL 값 특징 -> NULL 포함 산술연산은 항상 NULL임
SELECT A.SAL, A.SAL - NULL, A.EMPNO, A.EMPNO -NULL
FROM EMP A;

--DUAL TABLE
SELECT *
FROM DUAL;

-- DUAL TABLE 활용 예시
SELECT 'DATA' AS char_literal, 99 AS num_literal, DATE'2023-01-03' AS date_literal
FROM DUAL;


-- WHERE절 활용
SELECT *
	FROM EMP A
	WHERE A.SAL > 2000;


-- WHERE에 논리조건
SELECT *
	FROM EMP A
	WHERE A.SAL > 2000 
		OR A.HIREDATE > DATE'1982-01-01';

SELECT *
	FROM EMP A
	WHERE A.HIREDATE > DATE'1982-01-01'
		OR A.SAL > 2000;

SELECT *
	FROM EMP A
	WHERE A.HIREDATE > DATE'1982-01-01'
		OR A.SAL > 2000 
		AND A.JOB = 'CLERK';
    
SELECT *
	FROM EMP A
	WHERE A.HIREDATE > DATE'1982-01-01'
		OR (A.SAL > 2000 
		AND A.JOB = 'CLERK');
